# Generated by Django 6.0.4 on 2026-04-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_feedbackresponse_surveyresponse_delete_choice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackResponse',
        ),
    ]
