# Generated by Django 6.0.4 on 2026-04-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_1', models.TextField(blank=True, null=True)),
                ('f_2', models.TextField(blank=True, null=True)),
                ('f_3', models.TextField(blank=True, null=True)),
                ('f_4', models.TextField(blank=True, null=True)),
                ('f_5', models.TextField(blank=True, null=True)),
                ('f_6', models.TextField(blank=True, null=True)),
                ('f_7', models.TextField(blank=True, null=True)),
                ('f_8', models.TextField(blank=True, null=True)),
                ('f_9', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback Response',
                'verbose_name_plural': 'Feedback Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-binary'), ('prefer-not-to-say', 'Prefer not to say'), ('other', 'Other')], max_length=20, null=True)),
                ('sec1_q1', models.CharField(blank=True, max_length=30, null=True)),
                ('sec1_q2', models.CharField(blank=True, max_length=10, null=True)),
                ('sec1_q3', models.CharField(blank=True, max_length=20, null=True)),
                ('sec1_q4', models.JSONField(blank=True, default=list)),
                ('sec2_q1', models.CharField(blank=True, max_length=20, null=True)),
                ('sec2_q2', models.CharField(blank=True, max_length=20, null=True)),
                ('sec2_q3', models.TextField(blank=True, null=True)),
                ('sec2_q4', models.CharField(blank=True, max_length=20, null=True)),
                ('sec2_q5', models.CharField(blank=True, max_length=20, null=True)),
                ('sec2_q6', models.CharField(blank=True, max_length=20, null=True)),
                ('sec2_q7', models.CharField(blank=True, max_length=20, null=True)),
                ('sec3_q1', models.CharField(blank=True, max_length=20, null=True)),
                ('sec3_q2', models.TextField(blank=True, null=True)),
                ('sec3_q3', models.CharField(blank=True, max_length=20, null=True)),
                ('sec4_q1', models.TextField(blank=True, null=True)),
                ('sec4_q2', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
